# Generated by Django 4.0.4 on 2022-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
