# Generated by Django 4.0.4 on 2022-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_watches_delete_new_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
