# Generated by Django 4.0.4 on 2022-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_watches_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
