# Generated by Django 4.0.4 on 2022-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_watches_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('series', models.CharField(max_length=50, verbose_name='Модель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('screen_diagonal', models.IntegerField(verbose_name='Диагональ экрана')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Магазин смартфонов',
                'verbose_name_plural': 'Магазин смартфонов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'ordering': ['-created_at'], 'verbose_name': 'Магазин часов', 'verbose_name_plural': 'Магазин часов'},
        ),
        migrations.AlterField(
            model_name='watches',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='series',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'unisex')], default='UNISEX', max_length=50, verbose_name='Пол'),
        ),
    ]
