# Generated by Django 4.0.4 on 2022-05-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_watchesmechanism_watches_mechanism'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchesmechanism',
            options={'ordering': ['mechanism'], 'verbose_name': 'Механизм часов', 'verbose_name_plural': 'Механизмы часов'},
        ),
    ]
