# Generated by Django 4.0.4 on 2022-05-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_watchesmechanism_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='mechanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.watchesmechanism', verbose_name='Механзм часов'),
        ),
    ]
