# Generated by Django 4.0.4 on 2022-05-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_watches_mechanism'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['-created_at'], 'verbose_name': 'товар из магазина смартфонов', 'verbose_name_plural': 'товар из магазина смартфонов'},
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'ordering': ['-created_at'], 'verbose_name': 'товар из магазина часов', 'verbose_name_plural': 'товары из магазина часов'},
        ),
    ]
