# Generated by Django 4.0.4 on 2022-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_phones_options_alter_watches_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['-created_at'], 'verbose_name': 'товар из магазина смартфонов', 'verbose_name_plural': 'товары из магазина смартфонов'},
        ),
        migrations.AddField(
            model_name='watches',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='sex',
            field=models.CharField(choices=[('Мужские', 'Мужские'), ('Женские', 'Женские'), ('Унисекс', 'Унисекс')], default='UNISEX', max_length=50, verbose_name='Пол'),
        ),
    ]
