# Generated by Django 4.0.4 on 2022-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_phones_options_watches_name_alter_watches_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchesBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Бренд часов',
                'verbose_name_plural': 'Бренды часов',
                'ordering': ['brand'],
            },
        ),
    ]
