# Generated by Django 4.0.4 on 2022-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_watchesbrand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchesBrand',
            new_name='WatchesCompany',
        ),
        migrations.AlterModelOptions(
            name='watchescompany',
            options={'ordering': ['company'], 'verbose_name': 'Компания изготовитель часов', 'verbose_name_plural': 'Компании изготовители часов'},
        ),
        migrations.RenameField(
            model_name='watchescompany',
            old_name='brand',
            new_name='company',
        ),
    ]
