# Generated by Django 4.0.4 on 2022-06-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_watchesbrand_watchescompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.watchescompany', verbose_name='Компания изготовитель часов'),
        ),
    ]
