# Generated by Django 4.0.5 on 2022-06-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_watches_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.watchescompany', verbose_name='Компания изготовитель часов'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='mechanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.watchesmechanism', verbose_name='Механзм часов'),
        ),
        migrations.AlterField(
            model_name='watchescompany',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
